--- #YAML:1.0
name:               WWW-Mechanize-Sleepy
version:            0.7
abstract:           A Sleepy Mechanize Agent
author:
    - Kostas Ntonas <kntonas@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    WWW::Mechanize:  1.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
