# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Mechanize-Sleepy
version:      0.6
version_from: Sleepy.pm
installdirs:  site
requires:
    WWW::Mechanize:                1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
